// Generated by CoffeeScript 1.10.0
Translator.altTitleCaser = {
  titleCase: function(str) {
    var term;
    if (!str) {
      return str;
    }
    this.smallWords || (this.smallWords = RegExp("^(" + (((function() {
      var i, len, ref, results;
      ref = Translator.titleCaseLowerCase;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        term = ref[i];
        results.push(term.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]\s*/g, "\\$&"));
      }
      return results;
    })()).join('|')) + ")$", "i"));
    return str.replace(/[A-Za-z0-9\u00C0-\u00FF]+[^\s-]*/g, (function(_this) {
      return function(match, index, title) {
        if (index > 0 && index + match.length !== title.length && match.search(_this.smallWords) > -1 && title.charAt(index - 2) !== ':' && (title.charAt(index + match.length) !== '-' || title.charAt(index - 1) === '-') && title.charAt(index - 1).search(/[^\s-]/) < 0) {
          return match.toLowerCase();
        }
        if (match.substr(1).search(/[A-Z]|\../) > -1) {
          return match;
        }
        return match.charAt(0).toUpperCase() + match.substr(1);
      };
    })(this));
  }
};
