// Generated by CoffeeScript 1.12.0
var Zotero, display, html;

Zotero = {
  BetterBibTeX: {
    CSL: CSL
  }
};

Zotero.BetterBibTeX.CSL.state = {
  opt: {
    lang: 'en'
  },
  locale: {
    en: {
      opts: {
        'skip-words': Zotero.BetterBibTeX.CSL.SKIP_WORDS,
        'skip-words-regexp': new RegExp('(?:(?:[?!:]*\\s+|-|^)(?:' + Zotero.BetterBibTeX.CSL.SKIP_WORDS.map(function(term) {
          return term.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]\s*/g, '\\$&');
        }).join('|') + ')(?=[!?:]*\\s+|-|$))', 'g')
      }
    }
  }
};

Zotero.BetterBibTeX.CSL.titleCase = function(text) {
  return Zotero.BetterBibTeX.CSL.Output.Formatters.title(Zotero.Translate.Export.prototype.Sandbox.BetterBibTeX.CSL.state, text);
};

Translator.csquotes = {
  open: '‹«',
  close: '›»'
};

Translator.unicode = true;

Translator.BetterBibTeX = false;

Translator.BetterBibLaTeX = true;

Translator.titleCaseLowerCase = 'about above across afore after against along\nalongside amid amidst among amongst anenst apropos apud around as\naside astride at athwart atop barring before behind below beneath\nbeside besides between beyond but by circa despite down during\nexcept for forenenst from given in inside into lest like modulo\nnear next notwithstanding of off on onto out over per plus pro qua\nsans since than through thru throughout thruout till to toward\ntowards under underneath until unto up upon versus vs. v. vs v via\nvis-à-vis with within without according to ahead of apart from as\nfor as of as per as regards aside from back to because of close to\ndue to except for far from inside of instead of near to next to on\nto out from out of outside of prior to pursuant to rather than\nregardless of such as that of up to where as or yet so and nor a\nan the de d\' von van c et ca thru according ahead apart regards\nback because close due far instead outside prior pursuant rather\nregardless such their where'.replace(/\n/g, ' ').trim().split(/\s+/);

display = function(html, options) {
  var ast, cp, lang;
  console.log(html, options);
  ast = Translator.MarkupParser.parse(html, options);
  console.log(JSON.stringify(ast, null, 2));
  return;
  lang = ((options.language || '<none>') + '        ').substr(0, 8);
  console.log(options.source);
  console.log(lang + ": `" + html + "`");
  console.log(Translator.TitleCaser.titleCase(html));
  options.caseConversion = (options.language || 'en') === 'en';
  cp = LaTeX.text2latex(html, options);
  console.log("biblatex: {" + cp + "}");
  return console.log('');
};

html = '<i><span class=\"nocase\">Nodo unitatis et caritatis</span></i>: The <pre>Structure</pre> and Argument of Augustine\'s <i><span class=\"nocase\">De doctrina Christiana</span></i>';

html = "Hello <pre> hej </pre>";

display(html, {
  mode: 'html'
});

display(html, {
  caseConversion: true
});
